<html>
  <head>
    <title>Code Review :: </title>
    <style type="text/css">
    .body{background-color:White;}
    .summary{width:100%;font-weight:bold;background-color:White;border: thin solid #808000;color:#FAFCFE}
    .outer{font-weight:normal;color:#6D5757;background-color:#FFDFBF}
    .inner{font-weight:normal;color:black;}
    .reviewTable{border: thin solid #C0C0C0; width:100%}
    .headerRow{color:white;background-color: #800000;font-weight:bold;text-align: center}
    .reviewRow{background-color:#FFDFBF;color:black;}
    .rAligned{text-align:right;}
    .data{visibility:hidden}
  </style>
  </head>
  <body class="body">
    <div class="summary">
      <table>
        <tr>
          <td colspan="3" class="headerRow">Review Summary</td>
        </tr>
        <tr class="outer">
          <td>Project Name : <label class="inner" /></td>
          <td>Reviewed By : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Project Code : <label class="inner" /></td>
          <td>Reviewed Date : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Name : <label class="inner" /></td>
          <td>Status : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Version : <label class="inner" /></td>
          <td>Review Preparation Effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Size (ekloc) : <label class="inner" /></td>
          <td>Review effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Release Date for Review : <label class="inner" /></td>
          <td>Rework effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken By : <label class="inner" /></td>
          <td>Review Efficiency : <label class="inner">NaN</label></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken Date : <label class="inner" /></td>
          <td />
        </tr>
      </table>
      <table>
        <tr class="headerRow">
          <td colspan="2">Review Details</td>
          <td colspan="2">Defect Status Analysis</td>
          <td colspan="2">Defect Type Analysis</td>
          <td colspan="4">Defect Injected Phase Analysis</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td>Major</td>
          <td>Medium</td>
          <td>Minor</td>
        </tr>
        <tr class="outer">
          <td>Total No of Suggestions</td>
          <td class="inner">0</td>
          <td>Open</td>
          <td class="inner">0</td>
          <td>Logical</td>
          <td class="inner">0</td>
          <td>Initial Project Setup</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total No of Errors</td>
          <td class="inner">0</td>
          <td>On Hold</td>
          <td class="inner">0</td>
          <td>Incomplete</td>
          <td class="inner">0</td>
          <td>Project Initiation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total</td>
          <td class="inner">0</td>
          <td>Closed</td>
          <td class="inner">0</td>
          <td>UI</td>
          <td class="inner">0</td>
          <td>Requirement Analysis</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td>Rejected</td>
          <td class="inner">0</td>
          <td>Exception Handling</td>
          <td class="inner">0</td>
          <td>Architecture and Design</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td>Documentation</td>
          <td class="inner">0</td>
          <td>Implementation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>QA Testing</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>Transition Phase</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="rAligned">Total</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
      </table>
    </div>
    <br />
    <table class="reviewTable">
      <tr class="headerRow">
        <td>#</td>
        <td>Description</td>
        <td>Status</td>
        <td>DefectType</td>
        <td>InjectedPhase</td>
      </tr>
    </table>
    <div>
      <br />
    Created with <a href="http://visualstudiogallery.msdn.microsoft.com/d1e40c49-da36-42a5-8d5a-4ebe1feabbc9">ReviewPal</a></div>
    <div class="data">
      <Data id="ReviewPalData">
        <CodeReview xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <Reviews>
            <Smell>
              <Id>1</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.Model.MealControl.120</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>MealControl.cs</File>
              <Line>12</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>2</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.PresentationBackSideFormModel.132</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>PresentationBackSideFormModel.cs</File>
              <Line>10</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>3</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.SystemModel.139</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>SystemModel.cs</File>
              <Line>13</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>4</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.CustomerSideForm.263</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>POSCustomerSideForm.cs</File>
              <Line>16</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>5</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.CustomerSideForm.192</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>POSCustomerSideForm.Designer.cs</File>
              <Line>3</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>6</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.RestaurantSideForm.283</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>POSRestaurantSideForm.cs</File>
              <Line>15</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>7</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.Ordering_System.RestaurantSideForm.520</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>Ordering_System</Project>
              <File>POSRestaurantSideForm.Designer.cs</File>
              <Line>3</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
          </Reviews>
          <HashCodeIgnoreList />
          <AnalysisFileManager>
            <AnalysisFiles>
              <AnalysisFile>
                <RelativePath>Model\Category.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\CategoryControl.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\Meal.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\MealControl.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\Order.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\OrderControl.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\PageControl.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\PresentationBackSideFormModel.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\PresentationFrontSideFormModel.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\PresentationStartFormModel.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\SystemModel.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>POSCustomerSideForm.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>POSCustomerSideForm.Designer.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>POSRestaurantSideForm.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>POSRestaurantSideForm.Designer.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Program.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>StartUpForm.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>StartUpForm.Designer.cs</RelativePath>
                <ProjectName>Ordering_System</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>CategoryControlTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>CategoryTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MealControlTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MealTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>OrderControlTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>OrderTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PageControlTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationBackFromTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationFrontFormTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationStartFormTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>SystemModelTest.cs</RelativePath>
                <ProjectName>OrderTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>CodedUITest.cs</RelativePath>
                <ProjectName>UITest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>UITest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Robot.cs</RelativePath>
                <ProjectName>UITest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
            </AnalysisFiles>
          </AnalysisFileManager>
          <TotalLine>0</TotalLine>
        </CodeReview>
      </Data>
    </div>
  </body>
</html>