<html>
  <head>
    <title>Code Review :: </title>
    <style type="text/css">
    .body{background-color:White;}
    .summary{width:100%;font-weight:bold;background-color:White;border: thin solid #808000;color:#FAFCFE}
    .outer{font-weight:normal;color:#6D5757;background-color:#FFDFBF}
    .inner{font-weight:normal;color:black;}
    .reviewTable{border: thin solid #C0C0C0; width:100%}
    .headerRow{color:white;background-color: #800000;font-weight:bold;text-align: center}
    .reviewRow{background-color:#FFDFBF;color:black;}
    .rAligned{text-align:right;}
    .data{visibility:hidden}
  </style>
  </head>
  <body class="body">
    <div class="summary">
      <table>
        <tr>
          <td colspan="3" class="headerRow">Review Summary</td>
        </tr>
        <tr class="outer">
          <td>Project Name : <label class="inner" /></td>
          <td>Reviewed By : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Project Code : <label class="inner" /></td>
          <td>Reviewed Date : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Name : <label class="inner" /></td>
          <td>Status : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Version : <label class="inner" /></td>
          <td>Review Preparation Effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Size (ekloc) : <label class="inner" /></td>
          <td>Review effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Work Product Release Date for Review : <label class="inner" /></td>
          <td>Rework effort : <label class="inner" /></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken By : <label class="inner" /></td>
          <td>Review Efficiency : <label class="inner">NaN</label></td>
        </tr>
        <tr class="outer">
          <td>Review Action Taken Date : <label class="inner" /></td>
          <td />
        </tr>
      </table>
      <table>
        <tr class="headerRow">
          <td colspan="2">Review Details</td>
          <td colspan="2">Defect Status Analysis</td>
          <td colspan="2">Defect Type Analysis</td>
          <td colspan="4">Defect Injected Phase Analysis</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td>Major</td>
          <td>Medium</td>
          <td>Minor</td>
        </tr>
        <tr class="outer">
          <td>Total No of Suggestions</td>
          <td class="inner">0</td>
          <td>Open</td>
          <td class="inner">0</td>
          <td>Logical</td>
          <td class="inner">0</td>
          <td>Initial Project Setup</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total No of Errors</td>
          <td class="inner">0</td>
          <td>On Hold</td>
          <td class="inner">0</td>
          <td>Incomplete</td>
          <td class="inner">0</td>
          <td>Project Initiation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td>Total</td>
          <td class="inner">0</td>
          <td>Closed</td>
          <td class="inner">0</td>
          <td>UI</td>
          <td class="inner">0</td>
          <td>Requirement Analysis</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td>Rejected</td>
          <td class="inner">0</td>
          <td>Exception Handling</td>
          <td class="inner">0</td>
          <td>Architecture and Design</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td>Documentation</td>
          <td class="inner">0</td>
          <td>Implementation</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>QA Testing</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="inner" />
          <td>Transition Phase</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
        <tr class="outer">
          <td />
          <td />
          <td />
          <td />
          <td />
          <td />
          <td class="rAligned">Total</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
          <td class="inner">0</td>
        </tr>
      </table>
    </div>
    <br />
    <table class="reviewTable">
      <tr class="headerRow">
        <td>#</td>
        <td>Description</td>
        <td>Status</td>
        <td>DefectType</td>
        <td>InjectedPhase</td>
      </tr>
    </table>
    <div>
      <br />
    Created with <a href="http://visualstudiogallery.msdn.microsoft.com/d1e40c49-da36-42a5-8d5a-4ebe1feabbc9">ReviewPal</a></div>
    <div class="data">
      <Data id="ReviewPalData">
        <CodeReview xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <Reviews>
            <Smell>
              <Id>1</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.Model.212</HashCode>
              <Severity>Warning</Severity>
              <Weight>212</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>11</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>2</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.MouseEventModel.253</HashCode>
              <Severity>Warning</Severity>
              <Weight>253</Weight>
              <Project>DrawingModel</Project>
              <File>MouseEventModel.cs</File>
              <Line>9</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>3</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>68</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>4</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>70</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>5</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>164</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>6</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>165</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>7</Id>
              <SmellType>空白與空行-17</SmellType>
              <HashCode>SpacingAndNewLine17.GoogleDriveService.cs.2.            UserCredential credential;.            using (FileStream stream = new FileStream(_projectPath + clientSecretFileName, FileMode.Open, FileAccess.Read))</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>57</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>8</Id>
              <SmellType>Literal constants(字面常數)-"\\Resources"</SmellType>
              <HashCode>LiteralConstants._projectPath."\\Resources"</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>30</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>9</Id>
              <SmellType>Literal constants(字面常數)-"Error!"</SmellType>
              <HashCode>LiteralConstants.ShowMessage."Error!"</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>37</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>10</Id>
              <SmellType>Literal constants(字面常數)-2</SmellType>
              <HashCode>LiteralConstants.UploadFile.2</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>167</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>11</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.GoogleDriveService.237</HashCode>
              <Severity>Warning</Severity>
              <Weight>237</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>20</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>12</Id>
              <SmellType>變數-1</SmellType>
              <HashCode>Variable1.GoogleDriveService.SCOPES</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>22</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>13</Id>
              <SmellType>Unsuitable naming(名不符實)-contect(contect)</SmellType>
              <HashCode>UnsuitableNaming.GoogleDriveService.ShowMessage.contect</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>35</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>14</Id>
              <SmellType>Lack of omments(缺乏註解)</SmellType>
              <HashCode>LackOfComments</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>52</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>15</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveService.CreateNewService.25string applicationName;string clientSecretFileName;</HashCode>
              <Severity>Warning</Severity>
              <Weight>25</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>52</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>16</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveService.ListFileAndFolderWithQueryString.23string queryString;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>124</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>17</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveService.UploadFile.31string uploadFileName;string contentType;Action&lt;IUploadProgress&gt; uploadProgressEventHandler;Action&lt;Google.Apis.Drive.v2.Data.File&gt; responseReceivedEventHandler;</HashCode>
              <Severity>Red</Severity>
              <Weight>31</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>156</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>18</Id>
              <SmellType>函式-2</SmellType>
              <HashCode>Method2.GoogleDriveService.SubstractFileName</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>199</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>19</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveService.DownloadFile.21Google.Apis.Drive.v2.Data.File fileToDownload;string downloadPath;Action&lt;IDownloadProgress&gt; downloadProgressChangedEventHandler;</HashCode>
              <Severity>Warning</Severity>
              <Weight>21</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>217</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>20</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveService.UpdateFile.21string fileName;string fileId;string contentType;</HashCode>
              <Severity>Warning</Severity>
              <Weight>21</Weight>
              <Project>DrawingForm</Project>
              <File>GoogleDriveService.cs</File>
              <Line>264</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>21</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.Model.212</HashCode>
              <Severity>Warning</Severity>
              <Weight>212</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>11</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>22</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.MouseEventModel.253</HashCode>
              <Severity>Warning</Severity>
              <Weight>253</Weight>
              <Project>DrawingModel</Project>
              <File>MouseEventModel.cs</File>
              <Line>9</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>23</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>82</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>24</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>84</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>25</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>179</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>26</Id>
              <SmellType>空白與空行-9</SmellType>
              <HashCode>SpacingAndNewLine9</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>180</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>27</Id>
              <SmellType>Literal constants(字面常數)-"Error"</SmellType>
              <HashCode>LiteralConstants.ShowMessage."Error"</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>38</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>28</Id>
              <SmellType>Literal constants(字面常數)-"OK"</SmellType>
              <HashCode>LiteralConstants.ShowMessage."OK"</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>39</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>29</Id>
              <SmellType>Literal constants(字面常數)-2</SmellType>
              <HashCode>LiteralConstants.UploadFile.2</HashCode>
              <Severity>Warning</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>183</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>30</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingApp.GoogleDriveForApp.GoogleDriveServiceForApp.248</HashCode>
              <Severity>Warning</Severity>
              <Weight>248</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>22</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>31</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.CreateNewService.31string applicationName;string clientSecretFileName;</HashCode>
              <Severity>Red</Severity>
              <Weight>31</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>60</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>32</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.ListFileAndFolderWithQueryString.23string queryString;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>138</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>33</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.UploadFile.31string uploadFileName;string contentType;Action&lt;IUploadProgress&gt; uploadProgressEventHandler;Action&lt;Google.Apis.Drive.v2.Data.File&gt; responseReceivedEventHandler;</HashCode>
              <Severity>Red</Severity>
              <Weight>31</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>170</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>34</Id>
              <SmellType>函式-2</SmellType>
              <HashCode>Method2.GoogleDriveServiceForApp.SubstractFileName</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>213</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>35</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.GoogleDriveServiceForApp.UpdateFile.21string fileName;string fileId;string contentType;</HashCode>
              <Severity>Warning</Severity>
              <Weight>21</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>GoogleDriveServiceForApp.cs</File>
              <Line>274</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>36</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.Model.212</HashCode>
              <Severity>Warning</Severity>
              <Weight>212</Weight>
              <Project>DrawingModel</Project>
              <File>Model.cs</File>
              <Line>11</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>37</Id>
              <SmellType>Large class(過大類別)</SmellType>
              <HashCode>LargeClass.DrawingModel.MouseEventModel.253</HashCode>
              <Severity>Warning</Severity>
              <Weight>253</Weight>
              <Project>DrawingModel</Project>
              <File>MouseEventModel.cs</File>
              <Line>9</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>38</Id>
              <SmellType>Long method(過長函式)</SmellType>
              <HashCode>LongMethod.WindowsStoreGraphics.DrawArc.23double[] data;</HashCode>
              <Severity>Warning</Severity>
              <Weight>23</Weight>
              <Project>DrawingApp.Windows</Project>
              <File>WindowsStoreGraphics.cs</File>
              <Line>110</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
            <Smell>
              <Id>39</Id>
              <SmellType>變數-1</SmellType>
              <HashCode>Variable1.App.transitions</HashCode>
              <Severity>Red</Severity>
              <Weight>1</Weight>
              <Project>DrawingApp.Shared</Project>
              <File>App.xaml.cs</File>
              <Line>29</Line>
              <Comment />
              <Auto>false</Auto>
            </Smell>
          </Reviews>
          <HashCodeIgnoreList />
          <AnalysisFileManager>
            <AnalysisFiles>
              <AnalysisFile>
                <RelativePath>ButtonControl.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Circles.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ClearCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ColorCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>CommandManager.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DeleteCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DrawCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ICommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>IGraphics.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MouseEventModel.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MoveCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Rectangles.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ResizeCommand.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Shape.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Smiles.cs</RelativePath>
                <ProjectName>DrawingModel</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DoublePanel.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DrawingForm.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>DrawingForm.Designer.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Circles.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\ClearCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\ColorCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\CommandManager.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\DeleteCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\DrawCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\GoogleDriveService.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\ICommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\IGraphics.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Model.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\MouseEventModel.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\MoveCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Rectangles.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\ResizeCommand.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\shape.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\Smiles.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingModel\ButtonControl.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\PresentationModel.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\WindowsFormsGraphics.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Program.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\Resources1.Designer.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\Settings.Designer.cs</RelativePath>
                <ProjectName>DrawingForm</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>App.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.Shared</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingApp.Shared\App.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MainPage.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Circles.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\ClearCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\ColorCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\CommandManager.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\DeleteCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\DrawCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Model\GoogleDriveServiceForApp.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\ICommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\IGraphics.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Model.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\MouseEventModel.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\MoveCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Rectangles.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\ResizeCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Shape.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\Smiles.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\..\DrawingModel\ButtonControl.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\DrawCommand.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\PresentationModel.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>PresentationModel\WindowsStoreGraphics.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingApp.Windows</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>..\DrawingApp.Shared\App.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.WindowsPhone</ProjectName>
                <AnalysisFileType>Designer</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MainPage.xaml.cs</RelativePath>
                <ProjectName>DrawingApp.WindowsPhone</ProjectName>
                <AnalysisFileType>ViewOrController</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawingApp.WindowsPhone</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ButtonControlTest.cs</RelativePath>
                <ProjectName>DrawAnywhereUnitTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ModelTest.cs</RelativePath>
                <ProjectName>DrawAnywhereUnitTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>MouseEventTest.cs</RelativePath>
                <ProjectName>DrawAnywhereUnitTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>Properties\AssemblyInfo.cs</RelativePath>
                <ProjectName>DrawAnywhereUnitTest</ProjectName>
                <AnalysisFileType>Model</AnalysisFileType>
              </AnalysisFile>
              <AnalysisFile>
                <RelativePath>ShapeTest.cs</RelativePath>
                <ProjectName>DrawAnywhereUnitTest</ProjectName>
                <AnalysisFileType>Test</AnalysisFileType>
              </AnalysisFile>
            </AnalysisFiles>
          </AnalysisFileManager>
          <TotalLine>5892</TotalLine>
        </CodeReview>
      </Data>
    </div>
  </body>
</html>